export BUILT_PRODUCTS_DIR="/Users/tito/Library/Developer/Xcode/DerivedData/NanoStore-gievtfclhhfpiecmrdwfbrpgijyn/Build/Products/Debug"
export CURRENT_ARCH="x86_64"
export OBJECT_FILE_DIR_normal="/Users/tito/Library/Developer/Xcode/DerivedData/NanoStore-gievtfclhhfpiecmrdwfbrpgijyn/Build/Intermediates/NanoStore.build/Debug/UnitTestMac.build/Objects-normal"
export OBJROOT="/Users/tito/Library/Developer/Xcode/DerivedData/NanoStore-gievtfclhhfpiecmrdwfbrpgijyn/Build/Intermediates"
export SRCROOT="/Users/Shared/Dropbox/NanoStoreWorld/NanoStore2"
